language: objective-c
osx_image: xcode8.2
script:
 - xcodebuild -workspace Unlock.xcworkspace -scheme Unlock -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
 - xcodebuild test -workspace Unlock.xcworkspace -scheme Unlock -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'id=E40727B3-41FB-4D6E-B4CB-BFA87109EB12'
