#AppGratis Unlock Library - iOS Framework

This repo contains the code for the iOS Framework of AppGratis' Unlock Library.  
It allows you to manage features and resources provided by offers generated by https://AppGratis.github.io

## Language
Since Swift is still a moving target, this library is fully done in Objective-C.

## Building
Simply open `Unlock.xcworkspace` and build the framework. You'll probably need to set your team to sign it.

## Missing features
 - Cocoapods
 - Carthage
 - Documentation
   - How to integrate
   - How to use
   - Sample app
